; Auto-generated. Do not edit!


(cl:in-package heatmap_util-msg)


;//! \htmlinclude DroneFrissResult.msg.html

(cl:defclass <DroneFrissResult> (roslisp-msg-protocol:ros-message)
  ((data
    :reader data
    :initarg :data
    :type cl:float
    :initform 0.0))
)

(cl:defclass DroneFrissResult (<DroneFrissResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DroneFrissResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DroneFrissResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name heatmap_util-msg:<DroneFrissResult> is deprecated: use heatmap_util-msg:DroneFrissResult instead.")))

(cl:ensure-generic-function 'data-val :lambda-list '(m))
(cl:defmethod data-val ((m <DroneFrissResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader heatmap_util-msg:data-val is deprecated.  Use heatmap_util-msg:data instead.")
  (data m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DroneFrissResult>) ostream)
  "Serializes a message object of type '<DroneFrissResult>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'data))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DroneFrissResult>) istream)
  "Deserializes a message object of type '<DroneFrissResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'data) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DroneFrissResult>)))
  "Returns string type for a message object of type '<DroneFrissResult>"
  "heatmap_util/DroneFrissResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DroneFrissResult)))
  "Returns string type for a message object of type 'DroneFrissResult"
  "heatmap_util/DroneFrissResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DroneFrissResult>)))
  "Returns md5sum for a message object of type '<DroneFrissResult>"
  "fdb28210bfa9d7c91146260178d9a584")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DroneFrissResult)))
  "Returns md5sum for a message object of type 'DroneFrissResult"
  "fdb28210bfa9d7c91146260178d9a584")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DroneFrissResult>)))
  "Returns full string definition for message of type '<DroneFrissResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64 data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DroneFrissResult)))
  "Returns full string definition for message of type 'DroneFrissResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64 data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DroneFrissResult>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DroneFrissResult>))
  "Converts a ROS message object to a list"
  (cl:list 'DroneFrissResult
    (cl:cons ':data (data msg))
))
