; Auto-generated. Do not edit!


(cl:in-package heatmap_util-msg)


;//! \htmlinclude frissGoal.msg.html

(cl:defclass <frissGoal> (roslisp-msg-protocol:ros-message)
  ((get_data
    :reader get_data
    :initarg :get_data
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass frissGoal (<frissGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <frissGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'frissGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name heatmap_util-msg:<frissGoal> is deprecated: use heatmap_util-msg:frissGoal instead.")))

(cl:ensure-generic-function 'get_data-val :lambda-list '(m))
(cl:defmethod get_data-val ((m <frissGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader heatmap_util-msg:get_data-val is deprecated.  Use heatmap_util-msg:get_data instead.")
  (get_data m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <frissGoal>) ostream)
  "Serializes a message object of type '<frissGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'get_data) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <frissGoal>) istream)
  "Deserializes a message object of type '<frissGoal>"
    (cl:setf (cl:slot-value msg 'get_data) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<frissGoal>)))
  "Returns string type for a message object of type '<frissGoal>"
  "heatmap_util/frissGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'frissGoal)))
  "Returns string type for a message object of type 'frissGoal"
  "heatmap_util/frissGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<frissGoal>)))
  "Returns md5sum for a message object of type '<frissGoal>"
  "7c4a45fd84db64466a76461ae52ab3d2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'frissGoal)))
  "Returns md5sum for a message object of type 'frissGoal"
  "7c4a45fd84db64466a76461ae52ab3d2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<frissGoal>)))
  "Returns full string definition for message of type '<frissGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool get_data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'frissGoal)))
  "Returns full string definition for message of type 'frissGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool get_data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <frissGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <frissGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'frissGoal
    (cl:cons ':get_data (get_data msg))
))
