; Auto-generated. Do not edit!


(cl:in-package heatmap_util-msg)


;//! \htmlinclude GetPowerFrissFeedback.msg.html

(cl:defclass <GetPowerFrissFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback
    :reader feedback
    :initarg :feedback
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass GetPowerFrissFeedback (<GetPowerFrissFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GetPowerFrissFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GetPowerFrissFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name heatmap_util-msg:<GetPowerFrissFeedback> is deprecated: use heatmap_util-msg:GetPowerFrissFeedback instead.")))

(cl:ensure-generic-function 'feedback-val :lambda-list '(m))
(cl:defmethod feedback-val ((m <GetPowerFrissFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader heatmap_util-msg:feedback-val is deprecated.  Use heatmap_util-msg:feedback instead.")
  (feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GetPowerFrissFeedback>) ostream)
  "Serializes a message object of type '<GetPowerFrissFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'feedback) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GetPowerFrissFeedback>) istream)
  "Deserializes a message object of type '<GetPowerFrissFeedback>"
    (cl:setf (cl:slot-value msg 'feedback) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GetPowerFrissFeedback>)))
  "Returns string type for a message object of type '<GetPowerFrissFeedback>"
  "heatmap_util/GetPowerFrissFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GetPowerFrissFeedback)))
  "Returns string type for a message object of type 'GetPowerFrissFeedback"
  "heatmap_util/GetPowerFrissFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GetPowerFrissFeedback>)))
  "Returns md5sum for a message object of type '<GetPowerFrissFeedback>"
  "f1f168a39479bedb24dba7a087426182")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GetPowerFrissFeedback)))
  "Returns md5sum for a message object of type 'GetPowerFrissFeedback"
  "f1f168a39479bedb24dba7a087426182")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GetPowerFrissFeedback>)))
  "Returns full string definition for message of type '<GetPowerFrissFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GetPowerFrissFeedback)))
  "Returns full string definition for message of type 'GetPowerFrissFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GetPowerFrissFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GetPowerFrissFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GetPowerFrissFeedback
    (cl:cons ':feedback (feedback msg))
))
