// Auto-generated. Do not edit!

// (in-package heatmap_util.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class GetPowerFrissGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.index = null;
      this.new_origin = null;
    }
    else {
      if (initObj.hasOwnProperty('index')) {
        this.index = initObj.index
      }
      else {
        this.index = [];
      }
      if (initObj.hasOwnProperty('new_origin')) {
        this.new_origin = initObj.new_origin
      }
      else {
        this.new_origin = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GetPowerFrissGoal
    // Serialize message field [index]
    bufferOffset = _arraySerializer.int16(obj.index, buffer, bufferOffset, null);
    // Serialize message field [new_origin]
    bufferOffset = _serializer.bool(obj.new_origin, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GetPowerFrissGoal
    let len;
    let data = new GetPowerFrissGoal(null);
    // Deserialize message field [index]
    data.index = _arrayDeserializer.int16(buffer, bufferOffset, null)
    // Deserialize message field [new_origin]
    data.new_origin = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 2 * object.index.length;
    return length + 5;
  }

  static datatype() {
    // Returns string type for a message object
    return 'heatmap_util/GetPowerFrissGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'bf66fd7cb52c6c3592f291bd8c2212bd';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int16[] index
    bool new_origin
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GetPowerFrissGoal(null);
    if (msg.index !== undefined) {
      resolved.index = msg.index;
    }
    else {
      resolved.index = []
    }

    if (msg.new_origin !== undefined) {
      resolved.new_origin = msg.new_origin;
    }
    else {
      resolved.new_origin = false
    }

    return resolved;
    }
};

module.exports = GetPowerFrissGoal;
