// Auto-generated. Do not edit!

// (in-package heatmap_util.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class GetPowerFrissResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.data = null;
      this.size = null;
      this.source_coords = null;
    }
    else {
      if (initObj.hasOwnProperty('data')) {
        this.data = initObj.data
      }
      else {
        this.data = 0.0;
      }
      if (initObj.hasOwnProperty('size')) {
        this.size = initObj.size
      }
      else {
        this.size = 0;
      }
      if (initObj.hasOwnProperty('source_coords')) {
        this.source_coords = initObj.source_coords
      }
      else {
        this.source_coords = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GetPowerFrissResult
    // Serialize message field [data]
    bufferOffset = _serializer.float64(obj.data, buffer, bufferOffset);
    // Serialize message field [size]
    bufferOffset = _serializer.int16(obj.size, buffer, bufferOffset);
    // Serialize message field [source_coords]
    bufferOffset = _arraySerializer.int16(obj.source_coords, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GetPowerFrissResult
    let len;
    let data = new GetPowerFrissResult(null);
    // Deserialize message field [data]
    data.data = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [size]
    data.size = _deserializer.int16(buffer, bufferOffset);
    // Deserialize message field [source_coords]
    data.source_coords = _arrayDeserializer.int16(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 2 * object.source_coords.length;
    return length + 14;
  }

  static datatype() {
    // Returns string type for a message object
    return 'heatmap_util/GetPowerFrissResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '8a3f44e19130d36ab5f37e91f8827dfc';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    float64 data
    int16 size
    int16[] source_coords
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GetPowerFrissResult(null);
    if (msg.data !== undefined) {
      resolved.data = msg.data;
    }
    else {
      resolved.data = 0.0
    }

    if (msg.size !== undefined) {
      resolved.size = msg.size;
    }
    else {
      resolved.size = 0
    }

    if (msg.source_coords !== undefined) {
      resolved.source_coords = msg.source_coords;
    }
    else {
      resolved.source_coords = []
    }

    return resolved;
    }
};

module.exports = GetPowerFrissResult;
