// Auto-generated. Do not edit!

// (in-package heatmap_util.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class RvizFrissGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.get_data = null;
    }
    else {
      if (initObj.hasOwnProperty('get_data')) {
        this.get_data = initObj.get_data
      }
      else {
        this.get_data = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type RvizFrissGoal
    // Serialize message field [get_data]
    bufferOffset = _serializer.bool(obj.get_data, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type RvizFrissGoal
    let len;
    let data = new RvizFrissGoal(null);
    // Deserialize message field [get_data]
    data.get_data = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'heatmap_util/RvizFrissGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '7c4a45fd84db64466a76461ae52ab3d2';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    bool get_data
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new RvizFrissGoal(null);
    if (msg.get_data !== undefined) {
      resolved.get_data = msg.get_data;
    }
    else {
      resolved.get_data = false
    }

    return resolved;
    }
};

module.exports = RvizFrissGoal;
