// Generated by gencpp from file heatmap_util/DroneFrissGoal.msg
// DO NOT EDIT!


#ifndef HEATMAP_UTIL_MESSAGE_DRONEFRISSGOAL_H
#define HEATMAP_UTIL_MESSAGE_DRONEFRISSGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace heatmap_util
{
template <class ContainerAllocator>
struct DroneFrissGoal_
{
  typedef DroneFrissGoal_<ContainerAllocator> Type;

  DroneFrissGoal_()
    : index()  {
    }
  DroneFrissGoal_(const ContainerAllocator& _alloc)
    : index(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _index_type;
  _index_type index;





  typedef boost::shared_ptr< ::heatmap_util::DroneFrissGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::heatmap_util::DroneFrissGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DroneFrissGoal_

typedef ::heatmap_util::DroneFrissGoal_<std::allocator<void> > DroneFrissGoal;

typedef boost::shared_ptr< ::heatmap_util::DroneFrissGoal > DroneFrissGoalPtr;
typedef boost::shared_ptr< ::heatmap_util::DroneFrissGoal const> DroneFrissGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::heatmap_util::DroneFrissGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::heatmap_util::DroneFrissGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::heatmap_util::DroneFrissGoal_<ContainerAllocator1> & lhs, const ::heatmap_util::DroneFrissGoal_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::heatmap_util::DroneFrissGoal_<ContainerAllocator1> & lhs, const ::heatmap_util::DroneFrissGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace heatmap_util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::heatmap_util::DroneFrissGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heatmap_util::DroneFrissGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::heatmap_util::DroneFrissGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::heatmap_util::DroneFrissGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heatmap_util::DroneFrissGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heatmap_util::DroneFrissGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::heatmap_util::DroneFrissGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f8b05a6b9a8b5dfe93a04830672f732";
  }

  static const char* value(const ::heatmap_util::DroneFrissGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f8b05a6b9a8b5dfULL;
  static const uint64_t static_value2 = 0xe93a04830672f732ULL;
};

template<class ContainerAllocator>
struct DataType< ::heatmap_util::DroneFrissGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "heatmap_util/DroneFrissGoal";
  }

  static const char* value(const ::heatmap_util::DroneFrissGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::heatmap_util::DroneFrissGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int16[] index\n"
;
  }

  static const char* value(const ::heatmap_util::DroneFrissGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::heatmap_util::DroneFrissGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DroneFrissGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::heatmap_util::DroneFrissGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::heatmap_util::DroneFrissGoal_<ContainerAllocator>& v)
  {
    s << indent << "index[]" << std::endl;
    for (size_t i = 0; i < v.index.size(); ++i)
    {
      s << indent << "  index[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.index[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEATMAP_UTIL_MESSAGE_DRONEFRISSGOAL_H
