// Generated by gencpp from file heatmap_util/frissGoal.msg
// DO NOT EDIT!


#ifndef HEATMAP_UTIL_MESSAGE_FRISSGOAL_H
#define HEATMAP_UTIL_MESSAGE_FRISSGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace heatmap_util
{
template <class ContainerAllocator>
struct frissGoal_
{
  typedef frissGoal_<ContainerAllocator> Type;

  frissGoal_()
    : get_data(false)  {
    }
  frissGoal_(const ContainerAllocator& _alloc)
    : get_data(false)  {
  (void)_alloc;
    }



   typedef uint8_t _get_data_type;
  _get_data_type get_data;





  typedef boost::shared_ptr< ::heatmap_util::frissGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::heatmap_util::frissGoal_<ContainerAllocator> const> ConstPtr;

}; // struct frissGoal_

typedef ::heatmap_util::frissGoal_<std::allocator<void> > frissGoal;

typedef boost::shared_ptr< ::heatmap_util::frissGoal > frissGoalPtr;
typedef boost::shared_ptr< ::heatmap_util::frissGoal const> frissGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::heatmap_util::frissGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::heatmap_util::frissGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::heatmap_util::frissGoal_<ContainerAllocator1> & lhs, const ::heatmap_util::frissGoal_<ContainerAllocator2> & rhs)
{
  return lhs.get_data == rhs.get_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::heatmap_util::frissGoal_<ContainerAllocator1> & lhs, const ::heatmap_util::frissGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace heatmap_util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::heatmap_util::frissGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heatmap_util::frissGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::heatmap_util::frissGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::heatmap_util::frissGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heatmap_util::frissGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heatmap_util::frissGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::heatmap_util::frissGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c4a45fd84db64466a76461ae52ab3d2";
  }

  static const char* value(const ::heatmap_util::frissGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c4a45fd84db6446ULL;
  static const uint64_t static_value2 = 0x6a76461ae52ab3d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::heatmap_util::frissGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "heatmap_util/frissGoal";
  }

  static const char* value(const ::heatmap_util::frissGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::heatmap_util::frissGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"bool get_data\n"
;
  }

  static const char* value(const ::heatmap_util::frissGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::heatmap_util::frissGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.get_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct frissGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::heatmap_util::frissGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::heatmap_util::frissGoal_<ContainerAllocator>& v)
  {
    s << indent << "get_data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.get_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEATMAP_UTIL_MESSAGE_FRISSGOAL_H
