// Generated by gencpp from file heatmap_util/RvizFrissResult.msg
// DO NOT EDIT!


#ifndef HEATMAP_UTIL_MESSAGE_RVIZFRISSRESULT_H
#define HEATMAP_UTIL_MESSAGE_RVIZFRISSRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace heatmap_util
{
template <class ContainerAllocator>
struct RvizFrissResult_
{
  typedef RvizFrissResult_<ContainerAllocator> Type;

  RvizFrissResult_()
    : data()
    , size(0)  {
    }
  RvizFrissResult_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , size(0)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _data_type;
  _data_type data;

   typedef int16_t _size_type;
  _size_type size;





  typedef boost::shared_ptr< ::heatmap_util::RvizFrissResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::heatmap_util::RvizFrissResult_<ContainerAllocator> const> ConstPtr;

}; // struct RvizFrissResult_

typedef ::heatmap_util::RvizFrissResult_<std::allocator<void> > RvizFrissResult;

typedef boost::shared_ptr< ::heatmap_util::RvizFrissResult > RvizFrissResultPtr;
typedef boost::shared_ptr< ::heatmap_util::RvizFrissResult const> RvizFrissResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::heatmap_util::RvizFrissResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::heatmap_util::RvizFrissResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::heatmap_util::RvizFrissResult_<ContainerAllocator1> & lhs, const ::heatmap_util::RvizFrissResult_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.size == rhs.size;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::heatmap_util::RvizFrissResult_<ContainerAllocator1> & lhs, const ::heatmap_util::RvizFrissResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace heatmap_util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::heatmap_util::RvizFrissResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heatmap_util::RvizFrissResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::heatmap_util::RvizFrissResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::heatmap_util::RvizFrissResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heatmap_util::RvizFrissResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heatmap_util::RvizFrissResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::heatmap_util::RvizFrissResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cf2e4aade105b07f617c7c61e3ce58c";
  }

  static const char* value(const ::heatmap_util::RvizFrissResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cf2e4aade105b07ULL;
  static const uint64_t static_value2 = 0xf617c7c61e3ce58cULL;
};

template<class ContainerAllocator>
struct DataType< ::heatmap_util::RvizFrissResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "heatmap_util/RvizFrissResult";
  }

  static const char* value(const ::heatmap_util::RvizFrissResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::heatmap_util::RvizFrissResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float64[] data\n"
"int16 size\n"
;
  }

  static const char* value(const ::heatmap_util::RvizFrissResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::heatmap_util::RvizFrissResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RvizFrissResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::heatmap_util::RvizFrissResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::heatmap_util::RvizFrissResult_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "size: ";
    Printer<int16_t>::stream(s, indent + "  ", v.size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEATMAP_UTIL_MESSAGE_RVIZFRISSRESULT_H
