// Generated by gencpp from file heatmap_util/RvizFrissGoal.msg
// DO NOT EDIT!


#ifndef HEATMAP_UTIL_MESSAGE_RVIZFRISSGOAL_H
#define HEATMAP_UTIL_MESSAGE_RVIZFRISSGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace heatmap_util
{
template <class ContainerAllocator>
struct RvizFrissGoal_
{
  typedef RvizFrissGoal_<ContainerAllocator> Type;

  RvizFrissGoal_()
    : origin()  {
    }
  RvizFrissGoal_(const ContainerAllocator& _alloc)
    : origin(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _origin_type;
  _origin_type origin;





  typedef boost::shared_ptr< ::heatmap_util::RvizFrissGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::heatmap_util::RvizFrissGoal_<ContainerAllocator> const> ConstPtr;

}; // struct RvizFrissGoal_

typedef ::heatmap_util::RvizFrissGoal_<std::allocator<void> > RvizFrissGoal;

typedef boost::shared_ptr< ::heatmap_util::RvizFrissGoal > RvizFrissGoalPtr;
typedef boost::shared_ptr< ::heatmap_util::RvizFrissGoal const> RvizFrissGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::heatmap_util::RvizFrissGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::heatmap_util::RvizFrissGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::heatmap_util::RvizFrissGoal_<ContainerAllocator1> & lhs, const ::heatmap_util::RvizFrissGoal_<ContainerAllocator2> & rhs)
{
  return lhs.origin == rhs.origin;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::heatmap_util::RvizFrissGoal_<ContainerAllocator1> & lhs, const ::heatmap_util::RvizFrissGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace heatmap_util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::heatmap_util::RvizFrissGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heatmap_util::RvizFrissGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::heatmap_util::RvizFrissGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::heatmap_util::RvizFrissGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heatmap_util::RvizFrissGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heatmap_util::RvizFrissGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::heatmap_util::RvizFrissGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d3cad660d9a7409b3609463f4ae2ca3a";
  }

  static const char* value(const ::heatmap_util::RvizFrissGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd3cad660d9a7409bULL;
  static const uint64_t static_value2 = 0x3609463f4ae2ca3aULL;
};

template<class ContainerAllocator>
struct DataType< ::heatmap_util::RvizFrissGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "heatmap_util/RvizFrissGoal";
  }

  static const char* value(const ::heatmap_util::RvizFrissGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::heatmap_util::RvizFrissGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int16[] origin\n"
;
  }

  static const char* value(const ::heatmap_util::RvizFrissGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::heatmap_util::RvizFrissGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.origin);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RvizFrissGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::heatmap_util::RvizFrissGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::heatmap_util::RvizFrissGoal_<ContainerAllocator>& v)
  {
    s << indent << "origin[]" << std::endl;
    for (size_t i = 0; i < v.origin.size(); ++i)
    {
      s << indent << "  origin[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.origin[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEATMAP_UTIL_MESSAGE_RVIZFRISSGOAL_H
